{% set name = "pyqmix" %}
{% set version = "2019.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37e066f71a7e0872bcfcdd4e65a296da1b5d297878ee546fe7e453babb9cdd1a

build:
  number: 1
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vvv ."

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cffi
    - ruamel.yaml
    - appdirs
    - pywin32  # [win]
    - future  # [py2k]

test:
  imports:
    - pyqmix

about:
  home: https://github.com/psyfood/pyqmix
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A wrapper for the Cetoni Qmix SDK
  description: |
    This Python package wraps the Cetoni Qmix pump and valve interface DLLs
    using CFFI.
  doc_url: https://pyqmix.readthedocs.io/
  dev_url: https://github.com/psyfood/pyqmix

extra:
  recipe-maintainers:
    - hoechenberger
    - ArndalAndersen
